### ISSUE TITLE
Can you take out the android:icon in the manifest of the demo?

### ISSUE THREAD

**Issue by CapitanRedBeard** [dbachelder/CreditCardEntry#14]
It is causing a really unnessary error for me:
Error:(46, 9) Attribute application@icon value=(@drawable/halplogo) from AndroidManifest.xml:46:9
Error:(46, 9) Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : Attribute application@icon value=(@drawable/halplogo) from AndroidManifest.xml:46:9
>     is also present at com.github.dbachelder:CreditCardEntry:v1.2.1:13:9 value=(@drawable/ic_launcher)
>     Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:44:5 to override

I have added tools:replace="android:icon" in application but I still get the error. It would be awesome if you could just delete that line since there is no point in a library having an icon. Thanks man!

**Comment by CapitanRedBeard** [comment]
@dbachelder Alternatively, you should not package the Demo module when building library .aar. A Library is not supposed to inject redundant/sample resources, styles, manifests and themes into library's user's projects.

**Comment by dbachelder** [comment]
I was getting that error as well, so I removed it back in april

https://github.com/dbachelder/CreditCardEntry/commit/c506433a5932c58286264589f608b7c3eb1e9e75

I'm curious why you are seeing this error and I am not.. 

What version of gradle/gradle plugin are you using?

**Comment by dbachelder** [comment]
@CapitanRedBeard when I unzip the aar I don't see any of the demo resources:

```
10:50 $ unzip CreditCardEntry-release.aar
Archive:  CreditCardEntry-release.aar
  inflating: AndroidManifest.xml
  inflating: classes.jar
  inflating: R.txt
   creating: aapt/
  inflating: aapt/AndroidManifest.xml
   creating: res/
   creating: res/anim/
  inflating: res/anim/cycle.xml
  inflating: res/anim/shake.xml
   creating: res/drawable/
  inflating: res/drawable/background_white.xml
   creating: res/drawable-hdpi/
  inflating: res/drawable-hdpi/amex.png
  inflating: res/drawable-hdpi/cc_back.png
  inflating: res/drawable-hdpi/diners_club.png
  inflating: res/drawable-hdpi/discover.png
  inflating: res/drawable-hdpi/master_card.png
  inflating: res/drawable-hdpi/unknown_cc.png
  inflating: res/drawable-hdpi/visa.png
   creating: res/drawable-mdpi/
  inflating: res/drawable-mdpi/amex.png
  inflating: res/drawable-mdpi/amex_back.png
  inflating: res/drawable-mdpi/cc_back.png
  inflating: res/drawable-mdpi/diners_club.png
  inflating: res/drawable-mdpi/discover.png
  inflating: res/drawable-mdpi/master_card.png
  inflating: res/drawable-mdpi/unknown_cc.png
  inflating: res/drawable-mdpi/visa.png
   creating: res/drawable-xhdpi/
  inflating: res/drawable-xhdpi/amex.png
  inflating: res/drawable-xhdpi/amex_back.png
  inflating: res/drawable-xhdpi/cc_back.png
  inflating: res/drawable-xhdpi/diners_club.png
  inflating: res/drawable-xhdpi/discover.png
  inflating: res/drawable-xhdpi/master_card.png
  inflating: res/drawable-xhdpi/unknown_cc.png
  inflating: res/drawable-xhdpi/visa.png
   creating: res/drawable-xxhdpi/
  inflating: res/drawable-xxhdpi/amex.png
  inflating: res/drawable-xxhdpi/cc_back.png
  inflating: res/drawable-xxhdpi/diners_club.png
  inflating: res/drawable-xxhdpi/discover.png
  inflating: res/drawable-xxhdpi/master_card.png
  inflating: res/drawable-xxhdpi/unknown_cc.png
  inflating: res/drawable-xxhdpi/visa.png
   creating: res/values/
  inflating: res/values/values.xml
   creating: res/values-v11/
  inflating: res/values-v11/values-v11.xml
   creating: res/values-v14/
  inflating: res/values-v14/values-v14.xml
   creating: res/values-v21/
  inflating: res/values-v21/values-v21.xml
  inflating: annotations.zip
   creating: assets/
   creating: aidl/
```

**Comment by dbachelder** [comment]
@CapitanRedBeard I just released v1.3.0... I had been building locally off the commit sha.. so perhaps there was an issue in that release that I hadn't noticed.

please give the new version a try and let me know.

**Comment by CapitanRedBeard** [comment]
My bad man! I was on 1.2.1, and the problem persisted. But 1.3.0 is working like a beaut

**Comment by dbachelder** [comment]
Huh.. must have had something funky in 1.2.1... thanks for catching it! I'm surprised no one else ran into it.
